// db/seed/guest/guest_seed.ts
// Guest and commerce seed content: branding, menus, prices, photos, and room QR codes
//
// All new fields below are additive extras (docs/m2/07): every existing export name, id and
// price is unchanged, except item-202's category, which the spec explicitly moves. New menu
// items ship without image_url — the guest kit's PlateTile renders a designed fallback instead
// (images.unsplash.com is blocked in this sandbox, so new photos can't be verified here; see
// scripts/verify-seed-images.mjs).

const BASE_REQUEST_PRESETS = {
  housekeeping: [
    { slug: 'towels', label: 'Extra towels' },
    { slug: 'cleaning', label: 'Room cleaning' },
    { slug: 'turndown', label: 'Turndown service' },
    { slug: 'linen', label: 'Fresh bed linen' },
  ],
  amenities: [
    { slug: 'toiletries', label: 'Toiletries kit' },
    { slug: 'pillows', label: 'Extra pillows' },
    { slug: 'iron', label: 'Iron and board' },
    { slug: 'water', label: 'Bottled water' },
  ],
  front_desk: [
    { slug: 'late-checkout', label: 'Late check-out' },
    { slug: 'taxi', label: 'Book a taxi' },
    { slug: 'luggage', label: 'Help with luggage' },
    { slug: 'wake-up', label: 'Wake-up call' },
  ],
  maintenance: [
    { slug: 'ac', label: 'AC not cooling' },
    { slug: 'tv-wifi', label: 'TV or Wi-Fi help' },
    { slug: 'plumbing', label: 'Plumbing issue' },
    { slug: 'lights', label: 'Lights not working' },
  ],
};

export const GUEST_HOTELS_SEED = [
  {
    id: 'hotel-001',
    slug: 'grand-azure',
    name: 'Grand Azure Resort & Spa',
    tagline: 'Luxury Coastal Sanctuary & Private Villas',
    logo_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=120&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&auto=format&fit=crop&q=80',
    currency: 'INR',
    tax_rate_percent: 18.0,
    service_charge_percent: 5.0,
    status: 'active',
    short_name: 'Grand Azure',
    accent: '#5EC4D6',
    time_zone: 'Asia/Kolkata',
    contact: {
      phone: '+91 832 555 0101',
      email: 'concierge@grandazure.example',
      address: 'Candolim Beach Road, North Goa, Goa 403515',
      gstin: '30AAACG0000A1Z5',
    },
    info: {
      wifi_name: 'GrandAzure-Guest',
      checkout_time: '11:00',
      breakfast_hours: '07:00–10:30 · Azure Terrace',
      pool_hours: '07:00–21:00 · Infinity pool',
      delivery_estimate: 'usually 25–35 min',
    },
    category_order: ['All-Day Gourmet Dining', 'Signature Grills', 'Indian Classics', 'Beverages & Mixology', 'Desserts'],
    request_presets: BASE_REQUEST_PRESETS,
  },
  {
    id: 'hotel-002',
    slug: 'heritage-palace',
    name: 'The Heritage Palace & Haveli',
    tagline: 'Regal Rajasthan Hospitality & Royal Suites',
    logo_url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=120&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&auto=format&fit=crop&q=80',
    currency: 'INR',
    tax_rate_percent: 18.0,
    service_charge_percent: 5.0,
    status: 'active',
    short_name: 'Heritage Palace',
    accent: '#E9A23B',
    time_zone: 'Asia/Kolkata',
    contact: {
      phone: '+91 291 555 0202',
      email: 'concierge@heritagepalace.example',
      address: 'Palace Road, Jodhpur, Rajasthan 342006',
      gstin: '08AAACH0000A1Z5',
    },
    info: {
      wifi_name: 'HeritagePalace-Guest',
      checkout_time: '12:00',
      breakfast_hours: '07:30–10:30 · Durbar Hall',
      pool_hours: '08:00–20:00 · Courtyard pool',
      delivery_estimate: 'usually 30–40 min',
    },
    category_order: ['Royal Heritage Feast', 'From the Tandoor', 'Palace Beverages', 'Mithai & Desserts'],
    request_presets: {
      ...BASE_REQUEST_PRESETS,
      amenities: [
        { slug: 'toiletries', label: 'Toiletries kit' },
        { slug: 'pillows', label: 'Extra pillows' },
        { slug: 'iron', label: 'Iron and board' },
        { slug: 'water', label: 'Copper jug of water' },
      ],
    },
  },
];

export const GUEST_MENU_SEED = [
  // ---------------------------------------------------------------------
  // Grand Azure Resort & Spa (hotel-001) — 18 items
  // ---------------------------------------------------------------------
  {
    id: 'item-001',
    hotel_id: 'hotel-001',
    category: 'All-Day Gourmet Dining',
    name: 'Artisan Avocado Sourdough Tartine',
    description: 'Crushed Hass avocado, organic microgreens, heirloom cherry tomatoes, cold-pressed olive drizzle.',
    price_paise: 55000, // ₹550.00
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&auto=format&fit=crop&q=80',
    is_veg: true,
    allergen_tags: ['Gluten'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-002',
    hotel_id: 'hotel-001',
    category: 'All-Day Gourmet Dining',
    name: 'Wood-Fired Truffle & Wild Mushroom Pizza',
    description: 'Hand-stretched sourdough crust, wild forest porcini, buffalo mozzarella, black truffle oil.',
    price_paise: 89000, // ₹890.00
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&auto=format&fit=crop&q=80',
    is_veg: true,
    allergen_tags: ['Dairy', 'Gluten'],
    is_available: true,
    featured: true,
  },
  {
    id: 'item-006',
    hotel_id: 'hotel-001',
    category: 'All-Day Gourmet Dining',
    name: 'Azure Club Sandwich',
    description: 'Triple-stacked roast chicken, fried egg and smoked bacon between toasted brioche, hand-cut fries on the side.',
    price_paise: 65000,
    is_veg: false,
    allergen_tags: ['Gluten', 'Eggs'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-007',
    hotel_id: 'hotel-001',
    category: 'All-Day Gourmet Dining',
    name: 'Kerala Prawn Moilee with Lace Appam',
    description: 'Tiger prawns simmered in coconut and curry-leaf gravy, served with delicate lace appam steamed to order.',
    price_paise: 115000,
    is_veg: false,
    allergen_tags: ['Shellfish'],
    is_available: true,
    featured: true,
  },
  {
    id: 'item-008',
    hotel_id: 'hotel-001',
    category: 'All-Day Gourmet Dining',
    name: 'Burrata, Heirloom Tomato & Basil Oil',
    description: 'Creamy burrata over sun-ripened heirloom tomatoes, torn basil and a bright basil oil drizzle.',
    price_paise: 72000,
    is_veg: true,
    allergen_tags: ['Dairy'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-003',
    hotel_id: 'hotel-001',
    category: 'Signature Grills',
    name: 'Coastal Grilled King Salmon',
    description: 'Herb-crusted Atlantic salmon fillet, asparagus spears, saffron-infused lemon butter emulsion.',
    price_paise: 125000, // ₹1,250.00
    image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500&auto=format&fit=crop&q=80',
    is_veg: false,
    allergen_tags: ['Fish', 'Dairy'],
    is_available: true,
    featured: true,
  },
  {
    id: 'item-009',
    hotel_id: 'hotel-001',
    category: 'Signature Grills',
    name: 'Tandoori Lobster Tail, Garlic Butter',
    description: 'Whole lobster tail marinated in Kashmiri chilli and yoghurt, char-grilled and finished with garlic butter.',
    price_paise: 245000,
    is_veg: false,
    allergen_tags: ['Shellfish', 'Dairy'],
    is_available: true,
    featured: true,
  },
  {
    id: 'item-010',
    hotel_id: 'hotel-001',
    category: 'Signature Grills',
    name: 'Charcoal Paneer Tikka, Mint Chutney',
    description: 'Smoky charcoal-grilled cottage cheese cubes, marinated in hung curd and spices, served with mint chutney.',
    price_paise: 69000,
    is_veg: true,
    allergen_tags: ['Dairy'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-011',
    hotel_id: 'hotel-001',
    category: 'Indian Classics',
    name: 'Butter Chicken & Garlic Naan',
    description: 'Tandoor-roasted chicken simmered in a velvety tomato-butter gravy, paired with garlic-scented naan.',
    price_paise: 89000,
    is_veg: false,
    allergen_tags: ['Dairy', 'Gluten'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-012',
    hotel_id: 'hotel-001',
    category: 'Indian Classics',
    name: 'Dal Makhani & Jeera Rice',
    description: 'Black lentils slow-simmered overnight with butter and cream, served with fragrant cumin-tempered rice.',
    price_paise: 62000,
    is_veg: true,
    allergen_tags: ['Dairy'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-013',
    hotel_id: 'hotel-001',
    category: 'Indian Classics',
    name: 'Hyderabadi Vegetable Dum Biryani',
    description: 'Layered basmati and garden vegetables slow-cooked in sealed dum style with saffron and fried onions.',
    price_paise: 68000,
    is_veg: true,
    allergen_tags: ['Dairy', 'Nuts'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-004',
    hotel_id: 'hotel-001',
    category: 'Beverages & Mixology',
    name: 'Fresh Royal Coconut Water',
    description: 'Chilled tender coconut water served in shell with chia seeds and mint sprig.',
    price_paise: 25000, // ₹250.00
    image_url: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=500&auto=format&fit=crop&q=80',
    is_veg: true,
    allergen_tags: [],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-014',
    hotel_id: 'hotel-001',
    category: 'Beverages & Mixology',
    name: 'Cold Brew with Coconut Cream',
    description: 'Slow-steeped cold brew coffee layered over silky coconut cream, served over ice.',
    price_paise: 32000,
    is_veg: true,
    allergen_tags: [],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-015',
    hotel_id: 'hotel-001',
    category: 'Beverages & Mixology',
    name: 'Watermelon & Mint Cooler',
    description: 'Fresh watermelon juice muddled with mint and lime, chilled and lightly sparkling.',
    price_paise: 28000,
    is_veg: true,
    allergen_tags: [],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-016',
    hotel_id: 'hotel-001',
    category: 'Beverages & Mixology',
    name: 'Masala Chai Pot for Two',
    description: 'Assam tea leaves simmered with cardamom, ginger and cloves, served with warm milk for two.',
    price_paise: 22000,
    is_veg: true,
    allergen_tags: ['Dairy'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-005',
    hotel_id: 'hotel-001',
    category: 'Desserts',
    name: 'Belgian Dark Chocolate Fondant',
    description: '70% Valrhona dark chocolate lava cake, Madagascan vanilla bean gelato.',
    price_paise: 45000, // ₹450.00
    image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=80',
    is_veg: false,
    allergen_tags: ['Dairy', 'Gluten', 'Eggs'],
    is_available: true,
    featured: true,
  },
  {
    id: 'item-017',
    hotel_id: 'hotel-001',
    category: 'Desserts',
    name: 'Alphonso Mango Kulfi',
    description: 'Traditional reduced-milk kulfi churned with Alphonso mango pulp and a hint of cardamom.',
    price_paise: 38000,
    is_veg: true,
    allergen_tags: ['Dairy', 'Nuts'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-018',
    hotel_id: 'hotel-001',
    category: 'Desserts',
    name: 'Espresso Tiramisu Jar',
    description: 'Layers of espresso-soaked ladyfingers and mascarpone cream, dusted with cocoa, set in a jar.',
    price_paise: 52000,
    is_veg: false,
    allergen_tags: ['Dairy', 'Gluten', 'Eggs'],
    is_available: true,
    featured: false,
  },

  // ---------------------------------------------------------------------
  // The Heritage Palace & Haveli (hotel-002) — 13 items
  // ---------------------------------------------------------------------
  {
    id: 'item-201',
    hotel_id: 'hotel-002',
    category: 'Royal Heritage Feast',
    name: 'Dal Baati Churma Thali',
    description: 'Traditional slow-cooked lentils, ghee-soaked baatis, spiced churma with royal accompaniments.',
    price_paise: 75000, // ₹750.00
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=80',
    is_veg: true,
    allergen_tags: ['Dairy', 'Gluten'],
    is_available: true,
    featured: true,
  },
  {
    id: 'item-203',
    hotel_id: 'hotel-002',
    category: 'Royal Heritage Feast',
    name: 'Jodhpuri Laal Maas with Bajra Roti',
    description: 'Slow-cooked Mathania chilli mutton, smoked with cloves and ghee, served with hand-patted millet roti.',
    price_paise: 119000,
    is_veg: false,
    allergen_tags: [],
    is_available: true,
    featured: true,
  },
  {
    id: 'item-204',
    hotel_id: 'hotel-002',
    category: 'Royal Heritage Feast',
    name: 'Gatte ki Sabzi with Missi Roti',
    description: 'Steamed gram-flour dumplings simmered in a tangy yoghurt gravy, served with spiced missi roti.',
    price_paise: 64000,
    is_veg: true,
    allergen_tags: ['Dairy', 'Gluten'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-205',
    hotel_id: 'hotel-002',
    category: 'Royal Heritage Feast',
    name: 'Ker Sangri with Makki Roti',
    description: 'Desert beans and wild berries slow-cooked Rajasthani style, paired with maize-flour roti.',
    price_paise: 59000,
    is_veg: true,
    allergen_tags: [],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-206',
    hotel_id: 'hotel-002',
    category: 'From the Tandoor',
    name: 'Mutton Seekh Kebab, Onion Rings',
    description: 'Hand-minced mutton skewers spiced with garam masala, char-grilled over coals with crisp onion rings.',
    price_paise: 99000,
    is_veg: false,
    allergen_tags: ['Dairy'],
    is_available: true,
    featured: true,
  },
  {
    id: 'item-207',
    hotel_id: 'hotel-002',
    category: 'From the Tandoor',
    name: 'Malai Paneer Tikka',
    description: 'Cottage cheese marinated in cream, cashew paste and green chilli, grilled to a smoky finish.',
    price_paise: 72000,
    is_veg: true,
    allergen_tags: ['Dairy', 'Nuts'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-208',
    hotel_id: 'hotel-002',
    category: 'From the Tandoor',
    name: 'Stuffed Tandoori Aloo',
    description: 'Baby potatoes stuffed with spiced paneer and nuts, roasted in the tandoor until golden.',
    price_paise: 56000,
    is_veg: true,
    allergen_tags: ['Dairy'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-209',
    hotel_id: 'hotel-002',
    category: 'Palace Beverages',
    name: 'Kesariya Thandai',
    description: 'Chilled milk infused with saffron, almonds, fennel and rose, a royal Rajasthani classic.',
    price_paise: 32000,
    is_veg: true,
    allergen_tags: ['Dairy', 'Nuts'],
    is_available: true,
    featured: true,
  },
  {
    id: 'item-210',
    hotel_id: 'hotel-002',
    category: 'Palace Beverages',
    name: 'Rose Sharbat with Basil Seeds',
    description: 'Rose-scented sharbat over soaked basil seeds, served chilled with a splash of lime.',
    price_paise: 24000,
    is_veg: true,
    allergen_tags: [],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-211',
    hotel_id: 'hotel-002',
    category: 'Palace Beverages',
    name: 'Spiced Masala Chaas',
    description: 'Churned buttermilk tempered with roasted cumin, curry leaf and fresh coriander.',
    price_paise: 18000,
    is_veg: true,
    allergen_tags: ['Dairy'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-202',
    hotel_id: 'hotel-002',
    category: 'Mithai & Desserts',
    name: 'Kesar Pista Saffron Kulfi',
    description: 'Rich reduced milk kulfi infused with Kashmiri saffron and crushed pistachios.',
    price_paise: 35000, // ₹350.00
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&auto=format&fit=crop&q=80',
    is_veg: true,
    allergen_tags: ['Dairy', 'Nuts'],
    is_available: true,
    featured: false,
  },
  {
    id: 'item-212',
    hotel_id: 'hotel-002',
    category: 'Mithai & Desserts',
    name: 'Ghevar with Saffron Rabri',
    description: 'Crisp honeycomb ghevar soaked in sugar syrup, topped with thickened saffron rabri.',
    price_paise: 42000,
    is_veg: true,
    allergen_tags: ['Dairy', 'Gluten'],
    is_available: true,
    featured: true,
  },
  {
    id: 'item-213',
    hotel_id: 'hotel-002',
    category: 'Mithai & Desserts',
    name: 'Moong Dal Halwa',
    description: 'Yellow lentils slow-roasted in ghee with milk and nuts until deeply caramelised.',
    price_paise: 38000,
    is_veg: true,
    allergen_tags: ['Dairy', 'Nuts'],
    is_available: true,
    featured: false,
  },
];
