import {
  HotelTenant,
  StaffMember,
  KitchenTicket,
  RoomRecord,
  ServiceRequest,
  StayFolio,
  DeviceConfig,
  AuditLogItem,
  MenuItem,
  SlaEscalationAlert,
} from "@/modules/ops/types";

export const SEED_HOTELS: HotelTenant[] = [
  {
    id: "h_901",
    name: "Grand Azure Resort & Spa",
    code: "GA-RESORT",
    plan: "Enterprise",
    rooms: 180,
    activeStays: 142,
    status: "ACTIVE",
    currency: "INR",
    mrrPaise: 4990000,
  },
  {
    id: "h_902",
    name: "The Palm Heritage Boutique",
    code: "PALM-HERITAGE",
    plan: "Boutique",
    rooms: 45,
    activeStays: 38,
    status: "ACTIVE",
    currency: "INR",
    mrrPaise: 1990000,
  },
  {
    id: "h_903",
    name: "Alpine Vista Chalet",
    code: "ALPINE-VISTA",
    plan: "Standard",
    rooms: 28,
    activeStays: 4,
    status: "ACTIVE",
    currency: "INR",
    mrrPaise: 1490000,
  },
  {
    id: "h_904",
    name: "Metro Boutique Suites",
    code: "METRO-SUITES",
    plan: "Trial",
    rooms: 15,
    activeStays: 0,
    status: "SUSPENDED",
    currency: "INR",
    mrrPaise: 0,
  },
];

export const SEED_STAFF: StaffMember[] = [
  {
    id: "usr_m3_souschef_01",
    hotelId: "h_901",
    name: "Marcus Vance",
    role: "sous_chef",
    roleTitle: "Sous Chef (Expediter)",
    department: "kitchen",
    station: "Hot Line #2",
    shift: "Morning A",
    pin: "1234",
  },
  {
    id: "usr_m3_chef_02",
    hotelId: "h_901",
    name: "Chef Marco Pierre",
    role: "line_cook",
    roleTitle: "Line Cook (Grill & Sauté)",
    department: "kitchen",
    station: "Grill Station #1",
    shift: "Morning A",
    pin: "5566",
  },
  {
    id: "usr_m3_desk_01",
    hotelId: "h_901",
    name: "Elena Garcia",
    role: "front_desk",
    roleTitle: "Lead Concierge & Billing",
    department: "desk",
    station: "Front Desk Counter 1",
    shift: "Day Shift",
    pin: "4321",
  },
  {
    id: "usr_m3_desk_02",
    hotelId: "h_901",
    name: "David Chen",
    role: "front_desk",
    roleTitle: "Night Auditor",
    department: "desk",
    station: "Night Operations Deck",
    shift: "Night B",
    pin: "7788",
  },
  {
    id: "usr_m3_hk_01",
    hotelId: "h_901",
    name: "Rosa Martinez",
    role: "housekeeping",
    roleTitle: "Housekeeping Supervisor",
    department: "housekeeping",
    station: "Floor 2 & 3 Dispatch",
    shift: "Day Shift",
    pin: "2345",
  },
  {
    id: "usr_m3_hk_02",
    hotelId: "h_901",
    name: "Juan Kim",
    role: "housekeeping",
    roleTitle: "Floor Attendant",
    department: "housekeeping",
    station: "Floor 2 West",
    shift: "Day Shift",
    pin: "6789",
  },
  {
    id: "usr_m3_gm_01",
    hotelId: "h_901",
    name: "Arthur Pendelton",
    role: "manager",
    roleTitle: "General Manager",
    department: "admin",
    station: "Executive Suite",
    shift: "All Shifts",
    pin: "9999",
  },
  {
    id: "usr_m1_superadm",
    hotelId: "h_901",
    name: "Platform Super Admin",
    role: "super_admin",
    roleTitle: "SaaS Control Lead",
    department: "admin",
    station: "Global Ops Deck",
    shift: "24/7",
    pin: "0000",
  },
];

export const INITIAL_KITCHEN_TICKETS: KitchenTicket[] = [
  {
    id: "ord_0421",
    hotelId: "h_901",
    ticketNumber: "#0421",
    roomNumber: "402",
    stayId: "st_9x7a402",
    guestName: "Priyah Sharma",
    placedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 12 * 60 * 1000).toISOString(), // 12m left - GREEN
    status: "pending",
    items: [
      {
        name: "Truffle Risotto",
        quantity: 2,
        modifiers: ["No mushrooms (Allergy)", "Extra parmesan"],
        allergens: ["Dairy"],
        notes: "Severe mushroom allergy",
      },
      {
        name: "Sparkling Water",
        quantity: 1,
        modifiers: ["Chilled", "Slice of Lime"],
      },
    ],
    note: "Guest anniversary celebration in suite",
    priority: false,
    vip: false,
  },
  {
    id: "ord_0422",
    hotelId: "h_901",
    ticketNumber: "#0422",
    roomNumber: "118",
    stayId: "st_9x7a118",
    guestName: "Alexander Wright",
    placedAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 4 * 60 * 1000).toISOString(), // 4m left - AMBER
    status: "accepted",
    items: [
      {
        name: "Wagyu Burger (Dry Aged)",
        quantity: 1,
        modifiers: ["Medium Rare", "Crispy Truffle Fries", "Brioche Bun"],
        allergens: ["Gluten", "Dairy"],
      },
      {
        name: "Diet Coke",
        quantity: 1,
        modifiers: ["Chilled glass", "Lemon wedge"],
      },
    ],
    note: "Deliver promptly to balcony",
    priority: false,
    vip: false,
    acceptedBy: "Chef Marco",
    acceptedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: "ord_0420",
    hotelId: "h_901",
    ticketNumber: "#0420",
    roomNumber: "305",
    stayId: "st_9x7a305",
    guestName: "Michael Vance",
    placedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(), // BREACHED - ROSE
    status: "preparing",
    items: [
      {
        name: "Club Sandwich (Triple Decker)",
        quantity: 2,
        modifiers: ["Extra Dijon mayo", "Toasted sourdough"],
        allergens: ["Gluten", "Egg"],
      },
      {
        name: "Fresh Orange Juice",
        quantity: 2,
        modifiers: ["No Ice", "Freshly squeezed"],
      },
    ],
    note: "Urgent VIP Guest - Flight departs at 3 PM",
    priority: true,
    vip: true,
    acceptedBy: "Marcus Vance",
    acceptedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: "ord_0419",
    hotelId: "h_901",
    ticketNumber: "#0419",
    roomNumber: "201",
    stayId: "st_9x7a201",
    guestName: "Elena Rostova",
    placedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
    status: "ready",
    items: [
      {
        name: "Grilled Norwegian Salmon",
        quantity: 1,
        modifiers: ["Steamed asparagus", "Lemon herb butter"],
        allergens: ["Fish", "Dairy"],
      },
      {
        name: "Caesar Salad",
        quantity: 1,
        modifiers: ["Anchovy dressing on the side"],
        allergens: ["Fish", "Gluten"],
      },
    ],
    priority: false,
    vip: false,
    acceptedBy: "Chef Marco",
  },
];

export const INITIAL_ROOMS: RoomRecord[] = [
  {
    id: "rm_201",
    hotelId: "h_901",
    roomNumber: "201",
    floor: 2,
    type: "King Deluxe",
    cleanStatus: "CLEAN",
    occupancyStatus: "OCC",
    attendant: "Rosa M",
    notes: "VIP guest checked in yesterday",
    lastUpdated: "12 mins ago",
  },
  {
    id: "rm_202",
    hotelId: "h_901",
    roomNumber: "202",
    floor: 2,
    type: "King Deluxe",
    cleanStatus: "DIRTY",
    occupancyStatus: "VAC",
    attendant: "Unassigned",
    notes: "Guest departed 11:30 AM",
    lastUpdated: "35 mins ago",
  },
  {
    id: "rm_203",
    hotelId: "h_901",
    roomNumber: "203",
    floor: 2,
    type: "Twin Bed",
    cleanStatus: "CLEING" as unknown as "CLEANING",
    occupancyStatus: "OCC",
    attendant: "Juan K",
    notes: "Deep linen turnaround in progress",
    lastUpdated: "Just now",
  },
  {
    id: "rm_204",
    hotelId: "h_901",
    roomNumber: "204",
    floor: 2,
    type: "Penthouse Suite",
    cleanStatus: "INSPECTED",
    occupancyStatus: "DEP",
    attendant: "Rosa M",
    notes: "Supervisor inspection passed with honors",
    lastUpdated: "5 mins ago",
  },
  {
    id: "rm_205",
    hotelId: "h_901",
    roomNumber: "205",
    floor: 2,
    type: "King Deluxe",
    cleanStatus: "OOO",
    occupancyStatus: "MAINT",
    attendant: "Robert T",
    notes: "AC Leak reported in ceiling unit. Parts on order.",
    lastUpdated: "1 hour ago",
  },
  {
    id: "rm_206",
    hotelId: "h_901",
    roomNumber: "206",
    floor: 2,
    type: "Executive Suite",
    cleanStatus: "CLEAN",
    occupancyStatus: "OCC",
    attendant: "Rosa M",
    notes: "Guest requested 3x feather pillows",
    lastUpdated: "8 mins ago",
  },
  {
    id: "rm_207",
    hotelId: "h_901",
    roomNumber: "207",
    floor: 2,
    type: "King Deluxe",
    cleanStatus: "DIRTY",
    occupancyStatus: "VAC",
    attendant: "Unassigned",
    notes: "Daily check-out turnover pending",
    lastUpdated: "40 mins ago",
  },
  {
    id: "rm_208",
    hotelId: "h_901",
    roomNumber: "208",
    floor: 2,
    type: "Executive Suite",
    cleanStatus: "CLEAN",
    occupancyStatus: "OCC",
    attendant: "Juan K",
    notes: "Do Not Disturb lamp active on door terminal",
    lastUpdated: "18 mins ago",
  },
];

export const INITIAL_SERVICE_REQUESTS: ServiceRequest[] = [
  {
    id: "req_042",
    hotelId: "h_901",
    roomNumber: "304",
    title: "Extra Bath Towels & Sparkling Mineral Water",
    category: "Towels",
    placedAt: new Date(Date.now() - 16 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(), // 6m overdue
    status: "created",
    urgency: "critical",
  },
  {
    id: "req_043",
    hotelId: "h_901",
    roomNumber: "206",
    title: "3x Extra Feather Pillows",
    category: "Pillows",
    placedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 11 * 60 * 1000).toISOString(), // 11m left
    status: "created",
    urgency: "normal",
  },
  {
    id: "req_044",
    hotelId: "h_901",
    roomNumber: "402",
    title: "Baby Crib & Soft Bedding Setup",
    category: "Crib",
    placedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 29 * 60 * 1000).toISOString(), // 29m left
    status: "acknowledged",
    assignedTo: "Rosa M",
    urgency: "normal",
  },
];

export const INITIAL_FOLIOS: StayFolio[] = [
  {
    id: "fol_101",
    hotelId: "h_901",
    roomNumber: "101",
    guestName: "Elena Rostova",
    phone: "+1 (555) 019-4821",
    checkIn: "24 Sep 2026",
    checkOut: "28 Sep 2026",
    stayToken: "st_9x7a101",
    status: "Checked In",
    isVip: true,
    totalNetPaise: 1563559,
    cgstPaise: 140721,
    sgstPaise: 140720,
    totalDuePaise: 1845000,
    items: [
      {
        id: "fi_01",
        description: "Room Charge (Nights 1 & 2 - Deluxe Suite)",
        timestamp: "25 Sep 14:00 UTC",
        amountPaise: 1200000,
        source: "System Auto",
        isLocked: true,
      },
      {
        id: "fi_02",
        description: "In-Room Dining #0382 (Truffle Tagliolini + San Pellegrino)",
        timestamp: "25 Sep 20:15 UTC",
        amountPaise: 245000,
        source: "Kitchen Pos",
        isLocked: true,
      },
      {
        id: "fi_03",
        description: "Spa Retreat - Deep Tissue 90m Massage",
        timestamp: "26 Sep 10:30 UTC",
        amountPaise: 450000,
        source: "Spa Desk",
        isLocked: true,
      },
      {
        id: "fi_04",
        description: "Courtesy Discount (Luggage Delay Recovery)",
        timestamp: "26 Sep 11:00 UTC",
        amountPaise: -50000,
        source: "Desk (Adj)",
        isLocked: false,
        auditNote: "Guest luggage delayed 45 mins upon check-in. Authorized by Duty GM.",
        authorizedBy: "Arthur Pendelton (GM)",
      },
    ],
  },
  {
    id: "fol_102",
    hotelId: "h_901",
    roomNumber: "102",
    guestName: "David Chen",
    phone: "+1 (555) 234-8901",
    checkIn: "26 Sep 2026",
    checkOut: "27 Sep 2026",
    stayToken: "st_9x7a102",
    status: "Active Due",
    isVip: false,
    totalNetPaise: 271186,
    cgstPaise: 24407,
    sgstPaise: 24407,
    totalDuePaise: 320000,
    items: [
      {
        id: "fi_05",
        description: "Overnight King Deluxe Base Room",
        timestamp: "26 Sep 12:00 UTC",
        amountPaise: 320000,
        source: "System Auto",
        isLocked: true,
      },
    ],
  },
  {
    id: "fol_204",
    hotelId: "h_901",
    roomNumber: "204",
    guestName: "Sarah Jenkins (VIP)",
    phone: "+44 20 7946 0912",
    checkIn: "22 Sep 2026",
    checkOut: "26 Sep 2026",
    stayToken: "st_9x7a204",
    status: "Check-Out",
    isVip: true,
    totalNetPaise: 3796610,
    cgstPaise: 341695,
    sgstPaise: 341695,
    totalDuePaise: 4480000,
    items: [
      {
        id: "fi_06",
        description: "Penthouse Suite (4 Nights Stay)",
        timestamp: "22 Sep 15:00 UTC",
        amountPaise: 4000000,
        source: "System Auto",
        isLocked: true,
      },
      {
        id: "fi_07",
        description: "Private Chef Terrace Tasting",
        timestamp: "24 Sep 21:00 UTC",
        amountPaise: 480000,
        source: "Kitchen Pos",
        isLocked: true,
      },
    ],
  },
  {
    id: "fol_305",
    hotelId: "h_901",
    roomNumber: "305",
    guestName: "Michael Vance",
    phone: "+1 (555) 987-1234",
    checkIn: "25 Sep 2026",
    checkOut: "29 Sep 2026",
    stayToken: "st_9x7a305",
    status: "Clean Ready",
    isVip: false,
    totalNetPaise: 0,
    cgstPaise: 0,
    sgstPaise: 0,
    totalDuePaise: 0,
    items: [],
  },
  {
    id: "fol_402",
    hotelId: "h_901",
    roomNumber: "402",
    guestName: "Priyah Sharma",
    phone: "+91 98201 44810",
    checkIn: "26 Sep 2026",
    checkOut: "30 Sep 2026",
    stayToken: "st_9x7a402",
    status: "Checked In",
    isVip: false,
    totalNetPaise: 1029661,
    cgstPaise: 92670,
    sgstPaise: 92669,
    totalDuePaise: 1215000,
    items: [
      {
        id: "fi_08",
        description: "Oceanview Terrace Room (Night 1)",
        timestamp: "26 Sep 14:00 UTC",
        amountPaise: 1215000,
        source: "System Auto",
        isLocked: true,
      },
    ],
  },
];

export const INITIAL_MENU_CATALOG: MenuItem[] = [
  {
    id: "mi_01",
    hotelId: "h_901",
    title: "Truffle Tagliolini",
    category: "Mains",
    pricePaise: 125000,
    taxRatePct: 18,
    isAvailable: true,
    description: "Handmade pasta, shaved black Périgord winter truffles, cultured butter sauce, 36-month Parmigiano-Reggiano.",
    allergens: ["Gluten", "Dairy", "Egg"],
    station: "Pasta & Sauté #1",
    slaTargetMinutes: 18,
  },
  {
    id: "mi_02",
    hotelId: "h_901",
    title: "Wagyu Sliders (3pcs)",
    category: "Starters",
    pricePaise: 95000,
    taxRatePct: 18,
    isAvailable: true,
    description: "Australian BMS 7+ Wagyu beef, toasted artisan brioche bun, sweet caramelized onion jam, truffle aioli.",
    allergens: ["Dairy", "Gluten"],
    station: "Grill Station #1",
    slaTargetMinutes: 14,
  },
  {
    id: "mi_03",
    hotelId: "h_901",
    title: "Tiramisu Classico",
    category: "Desserts",
    pricePaise: 45000,
    taxRatePct: 18,
    isAvailable: false,
    description: "Espresso-soaked Savoiardi ladyfingers, velvety mascarpone cream, dark cocoa dusting.",
    allergens: ["Dairy", "Gluten", "Egg"],
    station: "Pastry & Cold Prep",
    slaTargetMinutes: 8,
  },
  {
    id: "mi_04",
    hotelId: "h_901",
    title: "Sparkling San Pellegrino (750ml)",
    category: "Beverages",
    pricePaise: 35000,
    taxRatePct: 18,
    isAvailable: true,
    description: "Natural Italian sparkling mineral water, served chilled with choice of fresh citrus wedge.",
    allergens: [],
    station: "Beverage Bar Station",
    slaTargetMinutes: 5,
  },
  {
    id: "mi_05",
    hotelId: "h_901",
    title: "Late Night Artisan Pizza Margherita",
    category: "Late Night",
    pricePaise: 85000,
    taxRatePct: 18,
    isAvailable: true,
    description: "San Marzano D.O.P. tomatoes, fresh buffalo mozzarella, hand-torn sweet basil, cold-pressed olive oil.",
    allergens: ["Gluten", "Dairy"],
    station: "Pizza Stone Hearth",
    slaTargetMinutes: 15,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: "aud_01",
    hotelId: "h_901",
    timestamp: "2026-09-26T08:14:02Z",
    actorId: "usr_m3_staff_01",
    actorName: "Marcus Vance (Sous Chef)",
    eventType: "order.accepted",
    entityTarget: "ord_0421 (Room 402)",
    ipAddress: "192.241.14.82",
    traceId: "tr_91b72e0a",
    payload: {
      orderId: "ord_0421",
      roomNumber: "402",
      ticketNumber: "#0421",
      station: "Hot Line #2",
      acceptedDurationSeconds: 42,
    },
  },
  {
    id: "aud_02",
    hotelId: "h_901",
    timestamp: "2026-09-26T08:11:45Z",
    actorId: "usr_m1_superadm",
    actorName: "Platform Super Admin",
    eventType: "audit.support_access",
    entityTarget: "hotel_h901 (Grand Azure)",
    ipAddress: "104.28.192.11",
    traceId: "tr_44c10a99",
    payload: {
      sessionExpiresAt: "2026-09-26T08:26:45Z",
      grantedMinutes: 15,
      jwtKeyFingerprint: "sha256_9f410a82b",
      reason: "Quarterly PCI-DSS compliance verification",
    },
  },
  {
    id: "aud_03",
    hotelId: "h_901",
    timestamp: "2026-09-26T08:04:19Z",
    actorId: "usr_m3_desk_02",
    actorName: "David Chen (Night Auditor)",
    eventType: "folio.manual_discount",
    entityTarget: "fol_101 (-₹500 INR)",
    ipAddress: "192.241.14.90",
    traceId: "tr_f88019aa",
    payload: {
      folio_id: "fol_101",
      room_number: "101",
      guest_name: "Elena Rostova",
      adjustment_paise: -50000,
      reason: "Service Recovery (Delay): Guest luggage delayed 45 mins upon check-in",
      manager_override_verified: true,
      authorizer: "Arthur Pendelton (GM)",
    },
  },
  {
    id: "aud_04",
    hotelId: "h_901",
    timestamp: "2026-09-26T07:55:00Z",
    actorId: "guest_tok_84a",
    actorName: "Guest (Room 102)",
    eventType: "order.created",
    entityTarget: "ord_8920 (Room 102)",
    ipAddress: "172.56.21.04",
    traceId: "tr_61b89912",
    payload: {
      orderId: "ord_8920",
      total_items: 2,
      server_calculated_paise: 320000,
    },
  },
  {
    id: "aud_05",
    hotelId: "h_901",
    timestamp: "2026-09-26T07:42:11Z",
    actorId: "system_cron",
    actorName: "SLA Escalation Engine v3",
    eventType: "notification.escalated",
    entityTarget: "req_042 (Room 304)",
    ipAddress: "10.0.4.1",
    traceId: "tr_ee014798",
    payload: {
      serviceRequestId: "req_042",
      roomNumber: "304",
      slaThresholdMinutes: 10,
      overdueDurationMinutes: 6,
      escalatedToRole: "manager_duty_deck",
    },
  },
];

export const INITIAL_DEVICE_CONFIG: DeviceConfig = {
  id: "dev_tab_02",
  hotelId: "h_901",
  deviceName: "Kitchen Tablet #02 (Line 1)",
  assignedDept: "kitchen",
  assignedRole: "Kitchen Station Lead",
  mode: "shared",
  status: "Active & Bound",
  endpointUuid: "ep_sub_9841fba09118c7e901a",
  swVersion: "sw.js v3.0 (RUNNING)",
  lastPing: "Just now (42ms)",
  currentOperator: "Marcus Vance (Sous Chef)",
  shiftEndsIn: "2h 45m",
};

export const INITIAL_SLA_ALERTS: SlaEscalationAlert[] = [
  {
    id: "esc_01",
    hotelId: "h_901",
    roomNumber: "304",
    title: "Extra Towels & Cold Water Overdue",
    department: "housekeeping",
    overdueMinutes: 6,
    severity: "critical",
    reason: "No staff accepted within 10m SLA threshold",
    escalatedTo: "Manager Duty Deck",
    staffAssigned: "None",
  },
  {
    id: "esc_02",
    hotelId: "h_901",
    roomNumber: "102",
    title: "In-Room Dining #0412 SLA Warning",
    department: "kitchen",
    overdueMinutes: 2,
    severity: "warning",
    reason: "Ticket prep time exceeding 80% SLA window",
    escalatedTo: "Executive Expediter",
    staffAssigned: "Chef Marco",
  },
];

export const HOURLY_SERVICE_VOLUME = [
  { label: "08:00", value: 12 },
  { label: "10:00", value: 24 },
  { label: "12:00", value: 38 },
  { label: "14:00", value: 42 },
  { label: "16:00", value: 28 },
  { label: "18:00", value: 36 },
  { label: "20:00", value: 39 },
  { label: "22:00", value: 18 },
  { label: "24:00", value: 7 },
];

export const DEPT_RESPONSE_BENCHMARKS = [
  { label: "Front Desk", value: 2.1, goal: 3.0 },
  { label: "Kitchen", value: 11.4, goal: 15.0 },
  { label: "Housekeeping", value: 18.0, goal: 20.0 },
  { label: "Maintenance", value: 8.2, goal: 12.0 },
];
