// lib/guest/copy.ts
// Every guest UI string, verbatim from docs/m2/08-copy-deck.md §2. No inline strings in guest JSX —
// import from here instead. Voice: warm concierge, calm under failure, honest, specific, no emoji.

export const GUEST_COPY = {
  qr: {
    resolving: 'Unlocking your stay',
    slow: 'Still connecting… hotel Wi-Fi can be slow. Hang tight.',
    error: {
      title: "We couldn't connect",
      body: "Check that you're online, then try again. The Wi-Fi name is on your key card.",
    },
  },
  common: {
    retry: 'Try again',
    callDesk: 'Call the front desk',
    back: 'Back',
    money: {
      subtotal: 'Subtotal',
      tax: 'GST',
      serviceCharge: 'Service charge',
      total: 'Total',
    },
  },
  home: {
    greeting: {
      morning: (name: string) => `Good morning, ${name}`,
      afternoon: (name: string) => `Good afternoon, ${name}`,
      evening: (name: string) => `Good evening, ${name}`,
      noSession: (hotel: string) => `Welcome to ${hotel}`,
    },
    noSession: { body: 'Scan the QR code in your room to order and make requests.' },
    welcomeToast: (hotel: string) => `Welcome to ${hotel}. Your room is connected.`,
    quick: {
      dining: 'In-room dining',
      housekeeping: 'Housekeeping',
      amenities: 'Amenities',
      frontDesk: 'Front desk',
      bill: 'Your bill',
      activity: 'Activity',
      hints: {
        dining: 'Delivered to your door',
        housekeeping: 'Towels, cleaning, turndown',
        amenities: 'Toiletries, pillows, more',
        frontDesk: 'Taxis, late check-out',
        maintenance: 'AC, plumbing, repairs',
        bill: 'See and settle',
        activity: 'Orders and requests',
      },
    },
    chefsPicks: "Chef's picks",
    info: { wifi: (network: string) => `Wi-Fi · ${network} · Password on your key card` },
  },
  menu: {
    title: 'In-room dining',
    subtitle: (room: string, estimate: string) => `Delivered to ${room} · ${estimate}`,
    subtitleNoSession: 'Browse our menu',
    search: { placeholder: 'Search dishes' },
    vegOnly: 'Veg only',
    noResults: (q: string) => `No dishes match "${q}"`,
    clearSearch: 'Clear search',
    empty: 'The kitchen is resting right now. The front desk can help.',
    added: 'Added to your order',
    viewCart: 'View cart',
    unavailable: 'Unavailable right now',
    scanToOrder: 'Scan the QR code in your room to order',
  },
  item: {
    each: (price: string) => `${price} each`,
    note: { label: 'Note for the kitchen', placeholder: 'e.g. no chilli, extra crispy', add: 'Add note' },
    add: 'Add to order',
    update: 'Update order',
    removed: 'Removed from your order',
    allergens: (list: string) => `Contains: ${list}`,
    noAllergens: 'No listed allergens',
  },
  cart: {
    title: 'Your order',
    deliverTo: 'Deliver to',
    room: (room: string, hotel: string) => `${room} · ${hotel}`,
    addMore: 'Add more items',
    note: { label: 'Note for the kitchen' },
    summary: {
      total: 'Total',
      calculated: (hotel: string) => `Calculated by ${hotel}'s billing system.`,
      noQuote:
        "Taxes and service charge are added by the hotel. You'll see the exact total the moment you place your order.",
    },
    place: 'Place order',
    placing: 'Placing your order…',
    empty: { title: 'Your order is empty', body: 'Pick something delicious from the menu.', cta: 'Browse the menu' },
    error: {
      unavailable: (item: string) => `${item} is no longer available. We've taken it out of your order.`,
      rate: "You're ordering a little fast. Please try again in a moment.",
      offline: "You're offline. Your order is saved here, so try again when you're connected.",
      tooLong: 'Kitchen notes can be up to 500 characters.',
      generic: "Your order didn't go through. Please try again.",
    },
  },
  request: {
    title: 'How can we help?',
    subtitle: 'Our team is notified instantly.',
    category: {
      housekeeping: 'Housekeeping',
      amenities: 'Amenities',
      front_desk: 'Front desk',
      maintenance: 'Maintenance',
    },
    whatDoYouNeed: 'What do you need?',
    other: 'Something else',
    details: 'Details (optional)',
    detailsRequired: 'Tell us a little more (at least 3 characters).',
    urgent: "It's urgent",
    send: 'Send request',
    sending: 'Sending…',
    error: "Your request didn't go through. Please try again.",
  },
  activity: {
    title: 'Your activity',
    filters: { all: 'All', orders: 'Orders', requests: 'Requests' },
    empty: {
      title: 'Nothing here yet',
      body: 'Order something delicious or ask us for anything.',
      orderFood: 'Order food',
      makeRequest: 'Make a request',
    },
    emptyFiltered: (filterLabel: string) => `No ${filterLabel.toLowerCase()} yet`,
    error: "We couldn't load your activity.",
  },
  tracking: {
    items: 'Items',
    placedBanner: 'Order placed. The kitchen has been notified.',
    sentBanner: 'Request sent. The team has been notified.',
    placedAgo: (relative: string) => `Placed ${relative}`,
    live: 'Live',
    reconnecting: 'Reconnecting…',
    offline: 'Offline, showing last update',
    delay: {
      pending: "The kitchen is busy right now. Your order is in the queue, and this screen updates the moment it's accepted.",
      preparing: 'Taking a little longer than usual. Thank you for your patience.',
      request: 'Still waiting? The team has been notified, and you can also call the front desk.',
    },
    notFound: "We couldn't find this order.",
    notFoundRequest: "We couldn't find this request.",
    orderCancelled: 'Order cancelled',
    orderAgain: 'Order again',
    orderElse: 'Order something else',
    assignee: (name: string) => `${name} has your request`,
  },
  bill: {
    title: 'Your bill',
    unpaid: 'Unpaid',
    paid: 'Paid',
    testMode: 'Test mode. No real money moves.',
    payWith: 'Pay with',
    method: { card: 'Card · test card ending 4242', upi: 'UPI · resortbrain@testupi' },
    pay: (amount: string) => `Pay ${amount}`,
    processing: 'Processing securely…',
    error: "The payment didn't go through. You haven't been charged, so try again.",
    nothing: { title: 'Nothing on your bill yet', body: 'Anything you order will appear here.' },
    viewReceipt: 'View receipt',
  },
  receipt: {
    success: 'Payment successful',
    print: 'Print receipt',
    pdf: 'Save invoice (PDF)',
    share: 'Share',
    home: 'Back to home',
  },
  feedback: {
    title: 'How was everything?',
    tags: ['Fast service', 'Delicious food', 'Friendly staff', 'Clean room', 'Great value'] as const,
    comment: 'Tell us more (optional)',
    send: 'Send feedback',
    thanks: "Thank you. We've shared this with the team.",
    low: "We're sorry it wasn't perfect. The front desk is one tap away.",
  },
  rejoin: {
    expired: {
      headline: 'Your session has timed out',
      body: 'For your security, room sessions expire. Scan the QR code in your room to continue.',
    },
    revoked: {
      headline: 'Thanks for staying with us',
      body: 'Your stay has ended, so this room link is no longer active. We hope to welcome you back soon.',
    },
    checked_out: {
      headline: 'Thanks for staying with us',
      body: 'Your stay has ended, so this room link is no longer active. We hope to welcome you back soon.',
    },
    invalid: {
      headline: "This code isn't active",
      body: "It may belong to a room that isn't checked in yet. The front desk can help.",
    },
    default: {
      headline: "Let's reconnect you",
      body: 'Scan the QR code in your room to open your stay.',
    },
    howToScan: 'How to scan',
    scanTips: ['Open the camera', 'Point it at the card on your bedside table', 'Tap the link'] as const,
  },
  offline: {
    title: "You're offline",
    body: 'Your menu is saved on this device.',
    back: 'Back online',
  },
  install: {
    title: (hotel: string) => `Add ${hotel} to your home screen`,
    body: 'One tap back to room service, requests and your bill.',
    ios: { steps: ['Tap the Share icon', 'Choose "Add to Home Screen"', 'Tap "Add"'] as const },
    addToHomeScreen: 'Add to Home Screen',
    notNow: 'Not now',
  },
  update: {
    ready: 'A fresh version is ready',
    refresh: 'Refresh',
  },
  demo: { badge: 'Demo data' },
  session: { notYou: 'Not you? Leave this device' },
  theme: { toSunlight: 'Switch to Sunlight mode', toDark: 'Switch to dark mode' },
} as const;
